dev_db = "dev_db"
prod_db = "prod_db"
dev_db_server =	"dev_db_server"
prod_db_server = "prod_db_server"
sql_backup_directory = "sql_backup_directory" # this is a directory accessible to sql server where it backup files directly
sql_backup_share = "sql_backup_share" # this is exposed backup_directory G:\\Backup\\Db\\Express on ase_e
backup_dev_file	= "backup_dev_file"
backup_prod_file =	"backup_prod_file"
dev_db_file	= "dev_db_file"
dev_log_file = "dev_log_file"

[hosts]
[[hosts.hosts1]]
one_drive_folder = "oneDrive_folder"
one_drive_latest_version_folder = "oneDrive_latest_version_folder"

[[hosts.host2]]
one_drive_folder = "one_drive_folder"
one_drive_latest_version_folder = "one_drive_latest_version_folder"